version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - ~/docker/mongodb:/data/db
    deploy:
      resources:
        limits:
          memory: 50M
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: chatgpt-telegram-bot
    image: desnowy/chatgpt-telegram-bot:latest
    restart: always
    volumes:
      - ~/config:/config
    deploy:
      resources:
        limits:
          memory: 60M
    depends_on:
      - mongo

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    deploy:
      resources:
        limits:
          memory: 50M
    depends_on:
      - mongo
