telegram_token: ""
openai_api_key: ""
allowed_telegram_usernames: []  # if empty, the bot is available to anyone
new_dialog_timeout: 60000  # new dialog starts after timeout (in seconds)
openai_email: ""
openai_password: ""
use_stream: "True"